### ISSUE TITLE
Colorcolumn goes on top of the colored css

### ISSUE THREAD

**Issue by davidosomething** [chrisbra/Colorizer#43]
You have the same issue as [ap/vim-css-color](https://github.com/ap/vim-css-color)
https://github.com/ap/vim-css-color/issues/45

See screenshot: http://screencast.com/t/qqtngvASak

**Comment by chrisbra** [comment]
Hi davidosomething!

On Mi, 25 Feb 2015, davidosomething wrote:

> You have the same issue as
> [ap/vim-css-color](https://github.com/ap/vim-css-color)
> https://github.com/ap/vim-css-color/issues/45

True. But there is nothing I can do about. Highlighting priorities are 
mostly hardcoded in the Vim source. But even if one could modify those 
priorities, I would argue it's not a bug. Because highlighting a column 
will only work, if no other highlighting goes on top of that, otherwise 
other people might complain that the colorcolumn setting does not work.

Best,
Christian
-- 
Nicht weil die Dinge schwierig sind wagen wir sie nicht,
sondern weil wir sie nicht wagen sind sie schwierig.
